baseurl = "/"
languageCode = "es-es"
title = "José Ángel"
theme = "hugo-theme-casper"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "Otros sitio estático con Hugo"
  cover = "images/cover_1.jpg"
  author = "Joanh"
  authorlocation = "Madrid, Spain"
  authorwebsite = "https://joseangelheras.com"
  bio= "Bio"
  logo = "images/logo_1.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feeds.feedburner.com/..."
  githubName = "joanh"
  # twitterName = ""
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  [params.social]
    twitter = "your_twitter"
